package opennlp;

public enum Status {
	RECRUITING, NYRECRUITING, NOTRECRUITING,
	AVAILABLE_EA, ACTIVE_NR, COMPLETED, TERMINATED,
	SUSPENDED, WITHDRAWN, ENR_BY_INV, TEMP_NA_EA, NA_EA,
	APPROVED, UNKNOWN;
}
